site_name: Hello Robbie
site_url: https://hello-robbie.github.io/
theme:
  name: cinder

nav:
  - Home: index.md
  - Resume: resume.md
  - Blog:
      - Why I Use Honeypots: blog/honeypots.md
      - Web App Default Paths: blog/webpaths.md

